# Generated by Django 4.0 on 2022-01-10 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=30)),
                ('i_photo', models.ImageField(upload_to='photos')),
                ('i_desc', models.TextField()),
                ('i_price', models.IntegerField()),
                ('i_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_quantity', models.IntegerField()),
                ('payment_type', models.CharField(max_length=30)),
                ('o_status', models.IntegerField()),
                ('o_date_time', models.DateTimeField(auto_now_add=True)),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('email_id', models.CharField(blank=True, max_length=30)),
                ('phone_no', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('height', models.CharField(max_length=15)),
                ('weight', models.CharField(max_length=15)),
                ('d_o_b', models.DateField(auto_now_add=True)),
                ('role', models.IntegerField()),
                ('status', models.IntegerField()),
                ('de_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deficiency')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.IntegerField()),
                ('comment', models.TextField()),
                ('f_date_time', models.DateTimeField(auto_now_add=True)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=30)),
                ('e_media', models.CharField(max_length=300)),
                ('de_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deficiency')),
            ],
        ),
        migrations.CreateModel(
            name='diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=30)),
                ('food_type', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=30)),
                ('weight_type', models.CharField(choices=[('Weight-gain', 'Weight-gain'), ('Weight-loose', 'Weight-loose')], max_length=30)),
                ('d_desc', models.TextField()),
                ('d_date_time', models.DateTimeField(auto_now_add=True)),
                ('de_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deficiency')),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=30)),
                ('b_desc', models.TextField()),
                ('b_like', models.IntegerField()),
                ('b_media', models.CharField(max_length=30)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
