# Generated by Django 3.2.9 on 2022-02-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_exercise_e_reps_exercise_e_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='d_o_b',
        ),
        migrations.AddField(
            model_name='login',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
