# Generated by Django 3.2.9 on 2022-02-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220225_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='wr_name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
