# Generated by Django 3.2.9 on 2022-02-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blog_wr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='calories',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
