# Generated by Django 3.2.9 on 2022-02-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_diet_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='time_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default=2, max_length=30),
            preserve_default=False,
        ),
    ]
