# Generated by Django 3.2.9 on 2022-02-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_diet_time_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='firstname',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
