# Generated by Django 3.2.9 on 2022-03-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='d_desc',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='e_media',
            field=models.FileField(upload_to='photos'),
        ),
    ]
