# Generated by Django 3.2.9 on 2022-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20220301_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='b_desc',
        ),
        migrations.AddField(
            model_name='blog',
            name='b_desc1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='b_desc2',
            field=models.TextField(default=''),
        ),
    ]
