# Generated by Django 3.2.9 on 2022-03-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_blog_b_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='d_date_time',
        ),
        migrations.AddField(
            model_name='diet',
            name='day',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='diet_time',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
    ]
