# Generated by Django 3.2.9 on 2022-03-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20220309_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='diet_time',
            field=models.CharField(max_length=30),
        ),
    ]
