# Generated by Django 3.2.9 on 2022-03-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_diet_diet_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='b_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='blog',
            name='wr_name',
            field=models.CharField(max_length=50),
        ),
    ]
