# Generated by Django 3.2.9 on 2022-03-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20220315_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='i_category',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
