# Generated by Django 3.2.9 on 2022-03-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_item_i_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='i_category',
        ),
    ]
