# Generated by Django 3.2.9 on 2022-03-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20220321_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='o_status',
            new_name='p_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='loginid',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='placeorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('o_date_time', models.DateTimeField(auto_now_add=True)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
            ],
        ),
    ]
