# Generated by Django 3.2.9 on 2022-03-22 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_placeorder_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='login',
            name='l_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
