# Generated by Django 4.0 on 2022-03-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20220322_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='p_status',
            new_name='total',
        ),
    ]
