# Generated by Django 3.2.9 on 2022-03-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_p_status_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
