from django.urls import path
from . import views

urlpatterns = [
    path('', views.index,name='index.html'),
    path('blog', views.blogs,name='blog.html'),
    path('checkout', views.checkout,name='checkout.html'),
    path('exercise', views.exercises,name='exercise.html'),
    path('login', views.loginpage,name='login.html'),
    path('products', views.products,name='products.html'),
    path('productcatwise/<int:id>', views.productcatwise,name='productcatwise'),
    path('register', views.register,name='register.html'),
    path('secblog/<int:id>', views.secblog,name='secblog.html'),
    path('single/<int:id>', views.single,name='single.html'),
    path('weightgain1', views.weightgain1,name='weightgain1.html'),
    path('weightgain2', views.weightgain2,name='weightgain2.html'),
    path('weightloose1', views.weightloose1,name='weightloose1.html'),
    path('weightloose2', views.weightloose2,name='weightloose2.html'),
    path('mailus', views.mailus,name='mail.html'),
    path('viewdata', views.viewdata, name='viewdata'),
    path('viewblg', views.viewblg, name='viewblg'),
    path('vwg', views.vwg, name='vwg'),
    path('vwgdaywise/<int:id>', views.vwgdaywise, name='vwgdaywise'),
    path('vwl', views.vwl, name='vwl'),
    path('vwldaywise/<int:id>', views.vwldaywise, name='vwldaywise'),
    path('nwg', views.nwg, name='nwg'),
    path('nwgdaywise/<int:id>', views.nwgdaywise, name='nwgdaywise'),
    path('nwl', views.nwl, name='nwl'),
    path('nwldaywise/<int:id>', views.nwldaywise, name='nwldaywise'),
    path('checkuser', views.checklogin, name='checkuser'),
    path('logout', views.logout, name='logout'),
    path('placeorderitem', views.placeorderitem, name='placeorderitem'),
    path('insertcontact', views.insertcontact, name='insertcontact'),
    path('insertfeedback', views.insertfeedback, name='insertfeedback'),
    path('addtocart/<int:id>', views.addtocart, name='addtocart'),
    path('vieworder/<int:id>', views.vieworder, name='vieworder'),
    path('order',views.vieworder,name='order.html'),
    path('deleteproduct/<int:id>', views.deleteproduct, name='deleteproduct'),
    path('ucart/<int:id>', views.ucart, name='ucart'),
    # path('viewadd/<int:id>', views.viewadd, name='viewadd'),
]